version: '3'

services:
  postgresdb:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mini_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  mini-auth:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
